- name:  Install tomcat7
  apt: name=tomcat7 state=present update_cache=yes cache_valid_time=3600

- name: Template Java 8 and memory size for tomcat
  template: src=tomcat7.j2 dest=/etc/default/tomcat7
  notify: restart tomcat7

- name: Copy over server.xml to disable autodeploy policy
  copy:
    src: server.xml
    dest: /var/lib/tomcat7/conf/server.xml
  notify: restart tomcat7
  
# handle user database
- include: populatedb.yml database=seqware_meta_db
    
# handle test database
- include: populatedb.yml database=test_seqware_meta_db

- include: ../../common/tasks/determine_seqware_version.yml

- name:  Copy xml webservice config
  copy: 
    src: seqware-webservice.xml
    dest: /etc/tomcat7/Catalina/localhost/SeqWareWebService.xml
  notify: restart tomcat7
  
- name: Rsync jars and xml config files
  command: rsync --itemize-changes {{ item.src }} {{ item.dest }}
  register: rsync_result
  with_items:
     - { src: '/home/seqware/gitroot/seqware/seqware-webservice/target/seqware-webservice-{{ det_seqware_version.stdout }}.war', dest: '/var/lib/tomcat7/webapps/SeqWareWebService.war' }
  changed_when: "rsync_result.stdout.startswith('>f+++++++++')"
  notify: restart tomcat7
