---
# file: roles/java/tasks/main.yml
- include: 'cloudera.yml'
  when: java_provider == "Cloudera"

- include: 'openjdk7.yml'
  when: java_provider == "OpenJDK7"

- include: 'oracle8.yml'
  when: java_provider == "Oracle8"
