---
# file: roles/java/tasks/oracle8.yml

- name: add repo for java 8
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: set licence selected
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes
  changed_when: false

- name: set licence seen
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
  sudo: yes
  changed_when: false

- name: install java 8
  apt: name=oracle-java8-installer state=latest update-cache=yes force=yes
  sudo: yes

- name: Java | Set up Java
  command: 'update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-8-oracle/jre/bin/java 2000'
  when: dpkg_result.changed

- name: Java | Set up Java
  command: 'update-alternatives --set java /usr/lib/jvm/java-8-oracle/jre/bin/java'
  when: dpkg_result.changed

- name: Java | Set up Jar
  command: 'update-alternatives --install /usr/bin/jar jar /usr/lib/jvm/java-8-oracle/bin/jar 2000'
  when: dpkg_result.changed

- name: Java | Set up Jar
  command: 'update-alternatives --set jar /usr/lib/jvm/java-8-oracle/bin/jar'
  when: dpkg_result.changed

- name: Java | Set JAVA_HOME
  lineinfile:
    line: 'JAVA_HOME=/usr/lib/jvm/java-8-oracle'
    dest: /etc/environment
    state: present
    create: yes
